#有关mysql配置
mysql:
  host: localhost
  port: 3306
  database: fipixelsync
  username: root
  password: 123456
  arguments: useSSL=false&useUnicode=true&characterEncoding=utf8
#有关redis配置
redis:
  #mysql启用的情况下该配置才有效
  host: localhost
  port: 6379
#如果需要用户名和密码可以手动配置
# username: root
# password: 123456