##本地存储 文件夹路径
local-storage-folder-path: "./plugins/FIPixelSync/data/"
## mysql
mysql:
  ## 启用mysql的情况下 本地存储会失效
  enable: false
  host: localhost
  port: 3306
  database: fipixelsync
  username: root
  password: 123456
#true的情况下会使插件在玩家数据变动的情况下进行数据的写入 默认false使用数据库的时候建议开启
high-frequency-writing: false